# frozen_string_literal: true

module RCAS
  # Gröbner bases.
  #
  #   G = groebner([x**2 + y**2 - 1, x - y], [x, y])   # reduced lex basis
  #   reduce(x**3, G, [x, y])                          # normal form; 0 iff x**3 is in the ideal
  #
  # Buchberger's algorithm with the product criterion (coprime leading
  # monomials give nothing new), normal forms by the multivariate division
  # algorithm, and the basis made reduced (minimal, inter-reduced, monic) at
  # the end. Monomial orders: :lex (the default, for elimination and
  # solving), :grlex, :grevlex; the variables are compared in the order given.
  #
  # Sources (keys: MANUAL.md, Sources): [Buc65]; [CLO15, ch. 2 §§3, 7, 9-10;
  # ch. 3 §1; ch. 5 §3]; [GCL92, ch. 10].
  module Groebner
    ORDERS = %i[lex grlex grevlex].freeze

    module_function

    # ---- monomial orders -------------------------------------------------------

    def order_key(exps, order)
      case order
      when :lex then exps
      when :grlex then [exps.sum, exps]
      when :grevlex then [exps.sum, exps.reverse.map(&:-@)]
      else raise ArgumentError, "unknown monomial order #{order.inspect}; use one of #{ORDERS.join(', ')}"
      end
    end

    # => [exponent vector, coefficient] of the leading term
    def leading(poly, order)
      e = poly.terms.keys.max_by { |k| order_key(k, order) }
      [e, poly.terms[e]]
    end

    def divides?(a, b) = a.zip(b).all? { |x, y| x <= y }

    # ---- division and S-polynomials --------------------------------------------

    # Normal form of f modulo the polynomials gs [CLO15, ch. 2 §3].
    def reduce(f, gs, order = :lex)
      ring = f.ring
      gs = gs.reject(&:zero?)
      leads = gs.map { |g| leading(g, order) }
      remainder = {}
      p = f
      until p.zero?
        ep, cp = leading(p, order)
        i = leads.index { |eg, _| divides?(eg, ep) }
        if i
          eg, cg = leads[i]
          shift = ep.zip(eg).map { |a, b| a - b }
          p -= Polynomial.new(ring, { shift => Scalar.div(cp, cg) }) * gs[i]
        else
          remainder[ep] = cp
          p -= Polynomial.new(ring, { ep => cp })
        end
      end
      Polynomial.new(ring, remainder)
    end

    def s_polynomial(f, g, order)
      ef, cf = leading(f, order)
      eg, cg = leading(g, order)
      l = ef.zip(eg).map(&:max)
      mf = Polynomial.new(f.ring, { l.zip(ef).map { |a, b| a - b } => Scalar.div(Num.new(1), cf) })
      mg = Polynomial.new(f.ring, { l.zip(eg).map { |a, b| a - b } => Scalar.div(Num.new(1), cg) })
      mf * f - mg * g
    end

    # ---- Buchberger ----------------------------------------------------------------

    # Reduced Gröbner basis of the ideal generated by polys (ring elements).
    def basis(polys, order = :lex)
      g = polys.reject(&:zero?)
      return [] if g.empty?
      ring = g.first.ring
      g = g.map { |p| monic(p.ring == ring ? p : p.to_ring(ring), order) }
      pairs = (0...g.size).to_a.combination(2).to_a
      until pairs.empty?
        i, j = pairs.shift
        next if coprime?(leading(g[i], order).first, leading(g[j], order).first) # product criterion
        s = reduce(s_polynomial(g[i], g[j], order), g, order)
        next if s.zero?
        g << s
        k = g.size - 1
        pairs.concat((0...k).map { |m| [m, k] })
        return [ring.one] if s.constant?
      end
      interreduce(g, order)
    end

    def coprime?(a, b) = a.zip(b).all? { |x, y| x.zero? || y.zero? }

    # Minimal (no leading monomial divides another), every element reduced
    # modulo the others, monic; sorted by leading monomial, largest first.
    def interreduce(g, order)
      sorted = g.reject(&:zero?).sort_by { |p| order_key(leading(p, order).first, order) }
      minimal = []
      sorted.each do |p|
        ep = leading(p, order).first
        minimal << p unless minimal.any? { |q| divides?(leading(q, order).first, ep) }
      end
      reduced = minimal.dup
      minimal.each_index do |i|
        others = reduced.each_with_index.reject { |_, j| j == i }.map(&:first)
        reduced[i] = monic(reduce(reduced[i], others, order), order)
      end
      reduced.sort_by { |p| order_key(leading(p, order).first, order) }.reverse
    end

    def monic(p, order)
      return p if p.zero?
      _, c = leading(p, order)
      Scalar.one?(c) ? p : p * Scalar.div(Num.new(1), c)
    end

    # ---- the ideal ------------------------------------------------------------------

    # Finitely many solutions? Every variable must be the leading monomial of
    # some basis element as a pure power [CLO15, ch. 5 §3, Theorem 6].
    def zero_dimensional?(basis, order = :lex)
      return false if basis.empty?
      n = basis.first.ring.vars.size
      (0...n).all? do |i|
        basis.any? do |p|
          e = leading(p, order).first
          e[i].positive? && e.each_with_index.all? { |v, j| j == i || v.zero? }
        end
      end
    end

    # ---- expression front end -----------------------------------------------------

    # groebner([f, g], [x, y]) with expressions: the ring is QQ[x, y], or
    # Frac(QQ[params])[x, y] when other symbols occur in the coefficients.
    def groebner(polys, vars = nil, order: :lex)
      _ring, elements = lift(polys, vars)
      basis(elements, order)
    end

    def normal_form(f, basis, vars = nil, order: :lex)
      _ring, elements = lift(basis + [f], vars)
      reduce(elements.last, elements[0...-1], order)
    end

    def lift(polys, vars)
      polys = Array(polys).map { |p| p.is_a?(Polynomial) ? p : Expression.lift(p) }
      if vars.nil? || Array(vars).empty?
        vars = polys.flat_map { |p| p.is_a?(Polynomial) ? p.ring.vars : p.variables }.uniq.sort
        raise ArgumentError, "groebner: no variables in #{polys.map(&:to_s).join(', ')}" if vars.empty?
      end
      vars = Array(vars).map { |v| v.is_a?(Var) ? v.name : v.to_sym }
      params = polys.flat_map { |p| p.is_a?(Polynomial) ? p.ring.vars : p.variables }.uniq - vars
      ring = params.empty? ? QQ[*vars] : QQ[*params].fraction_field[*vars]
      [ring, polys.map { |p| p.is_a?(Polynomial) ? p.to_ring(ring) : ring.call(p) }]
    end
  end
end
