# frozen_string_literal: true

# RCAS - a tiny symbolic algebra system that lives inside plain Ruby.
#
#   require "rcas"
#   e = (:x + 1) * (1 - :x)   # => (x + 1)*(1 - x)
#   e.expand                  # => 1 - x**2
#   e.diff(:x)                # => -2*x
#   e.call(x: 3)              # => -8
module RCAS
  VERSION = "0.1.0"
end

require_relative "rcas/expression"
require_relative "rcas/printer"
require_relative "rcas/simplify"
require_relative "rcas/expand"
require_relative "rcas/differentiate"
require_relative "rcas/functions"
require_relative "rcas/domains"
require_relative "rcas/scalar"
require_relative "rcas/polynomial"
require_relative "rcas/coefficients"
require_relative "rcas/gcd"
require_relative "rcas/factor"
require_relative "rcas/integrate"
require_relative "rcas/integrate_substitutions"
require_relative "rcas/constants"
require_relative "rcas/fraction"
require_relative "rcas/rational_function"
require_relative "rcas/number_theory"
require_relative "rcas/groebner"
require_relative "rcas/interpolate"
require_relative "rcas/solve"
require_relative "rcas/ode"
require_relative "rcas/series"
require_relative "rcas/summation"
require_relative "rcas/product"
require_relative "rcas/complex_parts"
require_relative "rcas/recurrence"
require_relative "rcas/poly_recurrence"
require_relative "rcas/petkovsek"
require_relative "rcas/zeilberger"
require_relative "rcas/q_functions"
require_relative "rcas/q_summation"
require_relative "rcas/q_difference"
require_relative "rcas/q_zeilberger"
require_relative "rcas/fps"
require_relative "rcas/laplace"
require_relative "rcas/geometry"
require_relative "rcas/analysis"
require_relative "rcas/numerics"
require_relative "rcas/statistics"
require_relative "rcas/special"
require_relative "rcas/precision"
require_relative "rcas/integral_functions"
require_relative "rcas/distributions"
require_relative "rcas/hypothesis"
require_relative "rcas/combinatorics"
require_relative "rcas/named_polynomials"
require_relative "rcas/inequalities"
require_relative "rcas/piecewise"
require_relative "rcas/fourier"
require_relative "rcas/trig"
require_relative "rcas/algebraic"
require_relative "rcas/finite_field"
require_relative "rcas/hold"
require_relative "rcas/steps"
require_relative "rcas/vector"
require_relative "rcas/matrix"
require_relative "rcas/poly_matrix"
require_relative "rcas/linear_algebra"
require_relative "rcas/decompositions"
require_relative "rcas/core_ext"
require_relative "rcas/latex"
require_relative "rcas/render"
require_relative "rcas/plot"
require_relative "rcas/background"
require_relative "rcas/results"
require_relative "rcas/docs"
